box_name: "default-server/jammy64"
name: test
hostname: test-server
username: "minex"
password: "123456"
memory: "1024"
cpu: 1
bridge_ip: "192.168.0.116"
bridge_gateway: "192.168.0.1"
host_ip: "192.168.59.103"
host_network: "VirtualBox Host-Only Ethernet Adapter #2"
