require 'yaml'

Vagrant.configure("2") do |config|
  # Load the YAML file and parse it
  config_data = YAML.load_file('config.yml')

  # Assign values from the YAML file
  box_name = config_data['box_name']
  name = config_data['name']
  hostname = config_data['hostname']
  memory = config_data['memory']
  cpu = config_data['cpu']
  bridge_ip = config_data['bridge_ip']
  host_ip = config_data['host_ip']
  host_network = config_data['host_network']


  # Base box for Ubuntu 22.04 (Jammy)
  config.vm.box = box_name

  # Set the hostname
  config.vm.hostname = hostname

  # VirtualBox provider configuration
  config.vm.provider "virtualbox" do |vb|
    vb.name = name
    vb.memory = memory
    vb.cpus = cpu
    # Set the graphics controller
    vb.customize ["modifyvm", :id, "--graphicscontroller", "VMSVGA"]
    # Enable USB
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "on"]
    # Set boot order to hard disk (hasddisk)
    vb.customize ["modifyvm", :id, "--boot1", "disk"]
  end

  # Network settings
  # Bridge network
  config.vm.network "public_network",
    type: "static",
    ip: bridge_ip,
    gateway: bridge_gw,
    netmask: "255.255.255.0",
    nameservers: ["8.8.8.8", "8.8.4.4"]

  # Host-only network
  # config.vm.network "private_network",
  #   type: "static",
  #   ip: host_ip,
  #   virtualbox__intnet: host_network

  # Disable the Shared folders
  config.vm.synced_folder ".", "/vagrant", disabled: true

end
